### Creation in Numpy

1. Create an array of Zeroes

In [5]:
import numpy as np

# np.zeros(size)
np.zeros(3) 

array([0., 0., 0.])

2. Create an Array of Ones

In [6]:
np.ones(4)

array([1., 1., 1., 1.])

3. Create an Array of 0’s and 1’s

In [7]:
np.array([1,0,0,0,1,0,1])

array([1, 0, 0, 0, 1, 0, 1])

4. Create an Array of 2’s

In [8]:
2*np.ones(5)

array([2., 2., 2., 2., 2.])

5. Create a NumPy Array of any Length

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

6. Reshape a NumPy Array into a Column Vector

In [11]:
# np.arange(size).reshape(size,1)

np.arange(9).reshape(9,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [12]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7. Generate Array of Random Numbers and in Grid Format

In [13]:
# np.random.randit(0, size, (x_dim, y_dim))

np.random.randint(0,9,(3,3))

array([[1, 1, 2],
       [0, 3, 8],
       [4, 8, 6]])

8 Create a Linspace

In [17]:
# Evenly spaced numbers np.linspace(start, stop, size)

np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

9. Create a Mesh Grid

In [19]:
# dense multi-dimensional mesh grid. np.mgrid[0:xdim, 0:ydim]

np.mgrid[0:3, 0:3]

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

### Reshaping in NumPy

In [20]:
Z = np.array([0,0,0,0,0,0,0,0,0,0,1,0])

# Z=np.array(1D_array).reshape(x_dimension,y_dimension)

1. Reshape to 12 rows and 1 column

In [22]:
m =  np.array(Z).reshape(12,1)
m

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0]])

2. Reshape to 6 rows and 2 columns

In [23]:
n = np.array(Z).reshape(6,2)
n

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0]])

### Indexing in NumPy

1. Get the First Value

In [24]:
Z = np.arange(9).reshape(3,3)
print(Z[0,0])

0


2. Get the Last Value

In [25]:
Z = np.arange(9).reshape(3,3)
print(Z[-1,-1])

8


3. Get a row from a Grid

In [26]:
# Z[row_index]
Z[2]

array([6, 7, 8])

4. Get a Column from a Grid

In [28]:
# Z[:, col_index]
Z[:,2]

array([2, 5, 8])

5. Get a Mini-grid from a Grid

In [30]:
# Z[row_index: , col_index:]
Z[1:,1:]

array([[4, 5],
       [7, 8]])

6. Arrange Values from a Grid in a Mini-grid

To get the values from corners of a grid and arrange them in a grid format write: Z[::row_size-1,::column_size-1]

In [31]:
Z[::2, ::2]

array([[0, 2],
       [6, 8]])

7. Get Specific Indices from a Grid

In [36]:
import numpy as np
Z = np.arange(9).reshape(3,3)
print(Z[[0,1],[0,2]]) # returns values at indices (0,0) and (1,2)

[0 5]


### Broadcasting in NumPy

General rules for Broadcasting#
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works its way forward. Two dimensions of size N are compatible when

- they are equal, or
- one of them is the singular value
- one is N * N and other is N * 1
- one is N * N and other is 1 * N

1. When one operand is N*N and other is 1 * 1

In [38]:
Z1 = np.arange(9).reshape(3,3)
Z2 = 1
Z1+Z2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2. When one operand is N * N and other is N * 1

In [41]:
Z1 = np.arange(9).reshape(3,3)
Z2 = np.arange(3)[::-1].reshape(3,1)
Z1 + Z2

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [44]:
np.arange(3)[::-1].reshape(3,1)

array([[2],
       [1],
       [0]])

3. When one operand is N * N and other is 1 * N

In [45]:
Z1 = np.arange(9).reshape(3,3)
Z2 = np.arange(3)[::-1]
Z1 + Z2

array([[2, 2, 2],
       [5, 5, 5],
       [8, 8, 8]])

### Indexing vs Fancy indexing

In [4]:
import numpy as np
Z = np.random.uniform(0,1,(5,5)) #draws sample from a uniform distribution
Z1 = Z[:3,:] # creates copy
print("Z1",Z1)
Z2 = Z[[0,1,2], :] # creates view
print("Z2",Z2)
print(np.allclose(Z1,Z2)) #returns True if two arrays are element-wise equal within a tolerance.
print(Z1.base is Z)#return true if memory of Z1 is shared with Z and false otherwise
print(Z2.base is Z)#return true if memory of Z2 is shared with Z and false otherwise
print(Z2.base is None) #return true if memory of Z2 is not shared

Z1 [[0.28098819 0.38842547 0.11724967 0.73257246 0.04010086]
 [0.32024075 0.53934554 0.23460956 0.67347368 0.57952596]
 [0.78253439 0.54318911 0.78054154 0.08230955 0.77465139]]
Z2 [[0.28098819 0.38842547 0.11724967 0.73257246 0.04010086]
 [0.32024075 0.53934554 0.23460956 0.67347368 0.57952596]
 [0.78253439 0.54318911 0.78054154 0.08230955 0.77465139]]
True
True
False
True
